name: Report

on:
  push:
    branches:
      - master
    paths:
      - 'src/**/*'
      - 'test/**/*'
      - 'karma.conf.js'

jobs:
  test:
    name: Code coverage report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install, test
        run: yarn install && npm run test
      - name: report code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
