name: Test

on: 
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Test before merge
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install, test
        run: yarn install && npm run test